### ISSUE TITLE
Is this connected to an API?

### ISSUE THREAD

**Issue by haydennyyy** [ericellb/React-Discord-Clone#1]
It looks like you make reference to a Heroku app, is that a backend that you've put on GitHub or not? Because I can't find one... I'd like to know what it does and the endpoints, so I could connect it to my own API

**Comment by ericellb** [comment]
I'll post a link later on.

**Comment by haydennyyy** [comment]
@ericellb I think that may be a private repo, mate. 404.

**Comment by ericellb** [comment]
Yeah I privates if because I realized I want escaping sql queries. Fixed
the scraping I'll unprivate.

**Comment by haydennyyy** [comment]
Any chance you're able to unprivate yet? @ericellb

**Comment by ericellb** [comment]
@haydennyyy Just did it.
