### ISSUE TITLE
Https Support?

### ISSUE THREAD

**Issue by Justsnoopy30** [ericellb/React-Discord-Clone#12]
It only runs on http, and I have no clue how to code typescript, only regular javascript.

**Comment by ericellb** [comment]
Hmm?

It runs on HTTPS. It's hosted on GH pages and Heroku.

**Comment by Justsnoopy30** [comment]
When it's run from nodejs, it's http

**Comment by Justsnoopy30** [comment]
@ericelib

**Comment by ericellb** [comment]
You can run it behind an Apache / Nginx webserver and use reverse proxy to get an HTTPS session between client and server.

Set up SSL on the webserver.

**Comment by Justsnoopy30** [comment]
But that's not native https on this itself.

**Comment by Justsnoopy30** [comment]
I actually already have nginx with a certain setup that requires the backend servers to be https.

**Comment by ericellb** [comment]
Sounds like a config issue on your hand. This properly works with a reverse proxy.

**Comment by Justsnoopy30** [comment]
It is purposely configured like this because of certain backends that need it like that. Plus, https should be default in projects like this.

**Comment by ericellb** [comment]
Im going to leave this with you https://stackoverflow.com/questions/42761992/configuring-https-for-express-and-nginx
