### ISSUE TITLE
Stuck on The server just woke up! Hold on for 5 seconds, while he munches a quick byte! Message

### ISSUE THREAD

**Issue by DodoGames7** [ericellb/React-Discord-Clone#18]
![image](https://user-images.githubusercontent.com/69091682/106037476-64337700-60df-11eb-93a2-99234eed22fb.png)
i stuck on this message

**Comment by ericellb** [comment]
The database was full, this has been fixed thanks

**Comment by DodoGames7** [comment]
thank you
