### ISSUE TITLE
This is really confusing 

### ISSUE THREAD

**Issue by gopal151295** [ericellb/React-Discord-Clone#2]
I am sure my password is of more than 6 character. Other than that,  it is highlighting username field instead of password.
![Screenshot from 2019-08-19 10-58-01](https://user-images.githubusercontent.com/17024637/63241164-40280100-c270-11e9-9508-7b8f917b3983.png)

**Comment by HolidayExplanation** [comment]
lol.

**Comment by ericellb** [comment]
Do you know how you reproduced this? 

I checked the code and that error is thrown on the backend only if pass is less than 6 chars.

I even tried with the same info in this pic and couldn't get the same issue reproduced

**Comment by gopal151295** [comment]
I have opened a pull request to fix this. 
https://github.com/ericellb/React-Discord-Clone/pull/3

**Comment by ericellb** [comment]
Merged PR https://github.com/ericellb/React-Discord-Clone/pull/3
