### ISSUE TITLE
I installed dompurify and I'm experience some errors that I don't know how to fix? 

### ISSUE THREAD

**Issue by BigBrainGuy1234** [ericellb/React-Discord-Clone#21]
C:/Users/apple/Desktop/React-Discord-Clone-master/discord-clone/src/components/Messages/Messages.tsx
TypeScript error in C:/Users/apple/Desktop/React-Discord-Clone-master/discord-clone/src/components/Messages/Messages.tsx(14,23):
Could not find a declaration file for module 'dompurify'. 'C:/Users/apple/Desktop/React-Discord-Clone-master/discord-clone/node_modules/dompurify/dist/purify.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/dompurify` if it exists or add a new declaration (.d.ts) file containing `declare module 'dompurify';`  TS7016

    12 | } from '@material-ui/core';
    13 | import moment from 'moment';
  > 14 | import DomPurify from 'dompurify';
       |                       ^
    15 | //import Code from 'react-code-prettify';
    16 | import UserInfo from '../UserInfo/UserInfo';
    17 | import { StoreState } from '../../reducers';

**Comment by CatMan6112** [comment]
i got that too, i just did `npm install dompurify` and it worked
